### ISSUE TITLE
Update 0.17

### ISSUE THREAD

**Issue by sebbi08** [Belaith/AutomaticLogisticChest#1]
Hi could you update the mod to 0.17 changing the factorio_version to 0.17 in the info.json sould be enought

**Comment by Belaith** [comment]
Changed in #https://github.com/Belaith/AutomaticLogisticChest/commit/f36e3c5b3aba23a6c9cf7c01e7485028a23c3811ac60896e01c9d68d5a8d9db4649f205aa6d969f7 but untested.
Feel free to open another Issue when you encounter any problems.

**Comment by sebbi08** [comment]
Thank you
